### ISSUE TITLE
Container display incorrect

### ISSUE THREAD

**Issue by noelmcgrath** [philicious/grafana-dashboards#1]
Hi, I am following Brians [article](https://www.brianchristner.io/updated-docker-monitoring-prometheus-grafana/) and imported your dashboard.
If I do docker ps I get 5 containers whereas the dashboard does not match up

See pic

![capture](https://cloud.githubusercontent.com/assets/671790/17268499/ddf9f69e-5622-11e6-8339-47f125e77ef9.PNG)

**Comment by philicious** [comment]
@noelmcgrath thats strange indeed. As Grafana is only querying Prometheus, you could go to `yourhost:9090/graph` and enter `container_last_seen{image!=""}` as expression. This will show you what Prometheus thinks is running. (and Prometheus knows by cAdvisor)
The query in Grafana is the aforementioned expression wrapped in `count(...)`

Lemme know if the count in Prometheus is also not matching

**Comment by noelmcgrath** [comment]
Prometheus  and grafana numbers match. However Prometheus  and cadvisor numbers do not. Must be Prometheus  issue

**Comment by philicious** [comment]
@noelmcgrath ok, to bad. closing this issue then.
